[package]
name = "ledger_sync_canister_impl"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>", "Matt Grogan <megrogan@gmail.com>", "Julian Jelfs <julian.jelfs@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
candid = "0.7.10"
canister_api_macros = { path = "../../../libraries/canister_api_macros" }
canister_logger = { path = "../../../libraries/canister_logger" }
canister_state_macros = { path = "../../../libraries/canister_state_macros" }
futures = "0.3.16"
http_request = { path = "../../../libraries/http_request" }
ic-cdk = "0.5.0"
ic-cdk-macros = "0.5.0"
ic-ledger-types = "0.1.1"
ledger_sync_canister = { path = "../api" }
ledger_utils = { path = "../../../libraries/ledger_utils" }
serde = "1.0.126"
serde_bytes = "0.11.5"
serializer = { path = "../../../libraries/serializer" }
tracing = "0.1.29"
types = { path = "../../../libraries/types", features = ["compression"] }
user_canister = { path = "../../user/api" }
user_canister_c2c_client = { path = "../../user/c2c_client" }
utils = { path = "../../../libraries/utils" }
