[package]
name = "user_canister"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>", "Matt Grogan <megrogan@gmail.com>", "Julian Jelfs <julian.jelfs@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = "0.7.14"
candid_gen = { path = "../../../libraries/candid_gen" }
ic-ledger-types = "0.1.1"
serde = "1.0.136"
serde_bytes = "0.11.5"
transaction_notifier = { git = "https://github.com/open-ic/transaction-notifier", rev = "65d3bbe1dbe8db9b46502795f20d43a88615ac39" }
types = { path = "../../../libraries/types" }